version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: strapi_db
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  strapi:
    build: ./backend
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_pass
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    volumes:
      - ./backend/public:/app/public

  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_STRAPI_URL: http://strapi:1337

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - strapi
      - nextjs

volumes:
  postgres_data:
